sudo: required
services:
   - docker
env:
   global:
      - SHA=$(git rev-parse HEAD)
      # - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
#    Command to install google cli to travis environment
#    - curl https://sdk.cloud.google.com | bash > /dev/null;
#    - source $HOME/google-cloud-sdk/path.bash.inc
#    - gcloud components update kubectl
#    - gcloud auth activate-service-account --key-file service-account.json
#    - gcloud config set project <Project ID>
#    - gcloud config set compute/zone us-central1-a
#    - gcloud container clusters get-credentials <name of cluster>
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker build -t hardik3296/react-test -f ./client/Dockerfile.dev ./client
script:
   - docker run -e CI=true hardik3296/react-test npm test
deploy:
   # Custom deployment
   provider: script
   script: bash ./deploy.sh
   on:
      branch: master